import localforage from 'https://cdn.skypack.dev/localforage';


// 5 built in 23andme files loaded to localforage, and used by get23meUrls() and get23().
let all23meURLS = localforage.createInstance({
    name: "all23meURLS",
    storeName: "all23meURLS"
})
let all23meFiles = localforage.createInstance({
    name: "all23meFiles",
    storeName: "all23meFiles"
})

const LOCAL_23ME_FILES = [
    "data/PGP_hu09B28E_genome_Joshua_Yoakem_v5_Full_20250127054538.txt",
    "data/PGP_hu0F2E0D_genome_Cajun_v5_Full_20231121192441.txt",
    "data/PGP_hu50801B_genome_Melinda_Chaperlo_v5_Full_20240728204807_(1).txt",
    "data/PGP_huAE4518_genome_Marika_Forsythe_v4_Full_20240826181111.txt",
    "data/PGP_huBE0518_genome_Christopher_Smith_v5_Full_20230926164611.txt"
]


// get all users with genotype data from local data folder-------------------------------
async function get23meUrls() {
    const newLocal = 'usersFull';
    let dt = await all23meURLS.getItem(newLocal); // check for users in localstorage
    if (dt == null) {
        const localUsers = LOCAL_23ME_FILES.map((file, index) => ({
            id: index + 1,
            name: file,
            genotypes: [
                {
                    id: index + 1,
                    filetype: "23andme",
                    download_url: file
                }
            ]
        }))
        dt = await all23meURLS.setItem(newLocal, localUsers)
    }
    return dt
}

// get 23andme text file from user url--------------------------------------------------------
// create 23andme obj and data --------------------------
async function parse23(txt, url) {
    // normally info is the file name
    let obj = {}
    let rows = txt.split(/[\r\n]+/g)
    obj.txt = txt
    obj.url = url

    let n = rows.filter(r => (r[0] == '#')).length
    obj.meta = rows.slice(0, n - 1).join('\r\n')
    obj.cols = rows[n - 1].slice(2).split(/\t/)
    obj.dt = rows.slice(n)
    obj.dt = obj.dt.map((r, i) => {
        r = r.split('\t')
        r[2] = parseInt(r[2])
        // position in the chr
        r[4] = i
        return r
    })
    return obj
}
async function get23(urls) {
    console.log('urls',urls)

    let data = {}
    let arrUrls = []
    let arr23Txts = []
    //console.log("getting all23me data from", urls.length, "23andMe urls:", urls)
    for (let i = 0; i < urls.length; i++) {
        let user = await all23meFiles.getItem(urls[i]);

        if (user == null) {
            let url2 = /^https?:\/\//.test(urls[i]) ? 'https://corsproxy.io/?' + urls[i] : urls[i]
            console.log('url2',url2)

            user = (await (await fetch(url2)).text())
            // console.log('user',user)

            all23meFiles.setItem(urls[i], user);
        }
        //console.log('checking 23andMe file #', i, " ...  ", urls[i], )

        if (user.substring(0, 37) == '# This data file generated by 23andMe') {
            //console.log("This is a valid 23andMe file:", user.substring(0, 37))
            let parsedUser = await parse23(user, urls[i])
            arr23Txts.push(parsedUser)
            console.log('parsedUser',parsedUser)

            arrUrls.push(urls[i])
        } else {
            //console.log("ERROR:This is NOT a valid 23andMe file:", user.substring(0, 37))
        }
    }
    // data["my23Txts"]  =  arr23Txts
    // data["my23Urls"]  =arrUrls
    // return data
    return arr23Txts
}


export {
    get23meUrls,
    get23,
    parse23
}