import localforage from "localforage";


// 5 built in 23andme files loaded to localforage, and used by get23meUrls() and get23().
let all23meURLS = localforage.createInstance({
    name: "all23meURLS",
    storeName: "all23meURLS"
})
let all23meFiles = localforage.createInstance({
    name: "all23meFiles",
    storeName: "all23meFiles"
})

const LOCAL_23ME_FILES = [
    "data/PGP_hu09B28E_genome_Joshua_Yoakem_v5_Full_20250127054538.txt",
    "data/PGP_hu0F2E0D_genome_Cajun_v5_Full_20231121192441.txt",
    "data/PGP_hu50801B_genome_Melinda_Chaperlo_v5_Full_20240728204807_(1).txt",
    "data/PGP_huAE4518_genome_Marika_Forsythe_v4_Full_20240826181111.txt",
    "data/PGP_huBE0518_genome_Christopher_Smith_v5_Full_20230926164611.txt"
]


// get all users with genotype data from local data folder-------------------------------
async function get23meUrls() {
    const newLocal = 'usersFull';
    let dt = await all23meURLS.getItem(newLocal); // check for users in localstorage
    if (dt == null) {
        const localUsers = LOCAL_23ME_FILES.map((file, index) => ({
            id: index + 1,
            name: file,
            genotypes: [
                {
                    id: index + 1,
                    filetype: "23andme",
                    download_url: file
                }
            ]
        }))
        dt = await all23meURLS.setItem(newLocal, localUsers)
    }
    return dt
}

// get 23andme text file from user url----------------------------
async function parse23(txt, url) {
    let obj = {}
    let rows = String(txt ?? "").split(/[\r\n]+/g).filter(Boolean)
    obj.txt = txt
    obj.url = url

    let n = rows.filter(r => r && r[0] == '#').length
    if (n === 0) {
        throw new Error(`Invalid 23andMe file format: missing header in ${url}`)
    }

    obj.meta = rows.slice(0, n - 1).join('\r\n')
    obj.cols = rows[n - 1].replace(/^#\s*/, '').split(/\t/)
    obj.dt = rows.slice(n)
    obj.dt = obj.dt.map((r, i) => {
        r = r.split('\t')
        r[2] = parseInt(r[2])
        // position in the chr
        r[4] = i
        return r
    })
    return obj
}

// load and parse 23andme files into SNP data
async function get23(urls) {
    console.log('urls',urls)

    let arr23Txts = []
    //console.log("getting all23me data from", urls.length, "23andMe urls:", urls)
    for (let i = 0; i < urls.length; i++) {
        const sourceUrl = urls[i]
        let user = await all23meFiles.getItem(sourceUrl);
        console.log('checking 23andMe file #', i + 1, " ...  ", sourceUrl, " (cached:", Boolean(user), ")")
        if (user == null) {
            let url2 = /^https?:\/\//.test(sourceUrl) ? 'https://corsproxy.io/?' + sourceUrl : sourceUrl
            console.log('url2',url2)

            const response = await fetch(url2)
            if (!response.ok) {
                continue
            }
            user = await response.text()

            await all23meFiles.setItem(sourceUrl, user);
        }
        //console.log('checking 23andMe file #', i, " ...  ", urls[i], )

        const userTxt = String(user ?? "")
        if (userTxt.startsWith('# This data file generated by 23andMe')) {
            let parsedUser = await parse23(userTxt, sourceUrl)
            arr23Txts.push(parsedUser)
            //console.log('parsedUser:',parsedUser)
        } else {
            //console.log("ERROR:This is NOT a valid 23andMe file:", user.substring(0, 37))
        }
    }
    // data["my23Txts"]  =  arr23Txts
    // data["my23Urls"]  =arrUrls
    // return data
    return arr23Txts
}


export {
    get23meUrls,
    get23,
    parse23
}